testbed_id: "${USER}-mysticeti"
cloud_provider:
  aws:
    specs: m5d.8xlarge
    token_file: "/Users/${USER}/.aws/credentials"
ssh_private_key_file: "/Users/${USER}/.ssh/aws"
regions:
  - us-west-1
repository:
  url: https://github.com/asonnino/mysticeti.git
  commit: main
